### ISSUE TITLE
Hi~Have you test your model in UCF101 and middlebury-other?

### ISSUE THREAD

**Issue by Re-bin** [CM-BF/FeatureFlow#10]
Could you please release your result on these two dataset?
Thank you so much! You have done a great job!

**Comment by CM-BF** [comment]
I'm currently trying to update the code and better the performance. It may cost some time because it is not my main project now. If you need these results urgently, I am afraid that I cannot provide them with a time guarantee. But I will add it after updating. 

Thank you!
