### ISSUE TITLE
About the paper

### ISSUE THREAD

**Issue by lhao0301** [CM-BF/FeatureFlow#2]
It looks amazing! But where can i find the paper?

**Comment by CM-BF** [comment]
We are preparing for the preprint. This page will be updated as soon as the paper is posted on arxiv. (See To Do List)

**Comment by lhao0301** [comment]
Look forward to it!

**Comment by CM-BF** [comment]
As the CVPR will release papers on its official website at the end of Mar, we decide not to post this paper on Arxiv. Instead, I have uploaded the paper and supplementary material **Here**. Please find it in the "paper" directory. : )
