### ISSUE TITLE
How to get the feature of the gound truth frame? 

### ISSUE THREAD

**Issue by liuzhidemaomao** [CM-BF/FeatureFlow#3]
Hello! I am confused when I was reading your source code. What is the architecture of the feature extractor for the gound truth frame? Is it just the same as the  feature extractor used in stage-I for frame0 and frame1? If not, then can you discribe how you implement it? Thanks!

**Comment by CM-BF** [comment]
Howdy! Yes, you are right. The feature extractors we used for two frames and the ground-truth frame are the same.
