### ISSUE TITLE
Cannot download the model

### ISSUE THREAD

**Issue by HeylonNHP** [CM-BF/FeatureFlow#4]
It's locked behind a chinese website (Baidu) which I cannot gain access to without being Chinese

**Comment by CM-BF** [comment]
You can download the model using Google Drive hyperlink rather than Baidu Cloud. Their contents are the same.

**Comment by RNubla** [comment]
Hi, the Google Drive link that was provided only contains the checkpoint not the model. Is there a way share the link for the model? Thank you

**Comment by RNubla** [comment]
@HeylonNHP You can Download the Model from here https://drive.google.com/file/d/1CmDMypSlLM6EAvOt5yjwUQ7O5w-xCm1n/view

**Comment by CM-BF** [comment]
@RNubla Thank you! I misunderstood his meaning before. I will add this link to README.

**Comment by RNubla** [comment]
@CM-BF No problem!
