### ISSUE TITLE
The mmdetection package  does not support mmdet.ops

### ISSUE THREAD

**Issue by lseiyjg** [CM-BF/FeatureFlow#5]
How can I solve it？ After I install the mmdetection, it does not work.

(py36torch13) [root@jiangzidong0407 FeatureFlow]# python sequence_run.py --checkpoint checkpoints/FeFlow.ckpt --video_path ../IMNet_FRC_FOR_HDVIDEO_lz/test_5/yw37.mp4 --t_interp 2
Traceback (most recent call last):
  File "sequence_run.py", line 10, in <module>
    import src.pure_network as layers
  File "/root/liuzheng/project/FeatureFlow/src/pure_network.py", line 1, in <module>
    import src.model as model
  File "/root/liuzheng/project/FeatureFlow/src/model.py", line 6, in <module>
    from mmdet.ops.dcn.deform_conv import DeformConv, ModulatedDeformConv, _pair, modulated_deform_conv
ModuleNotFoundError: No module named 'mmdet.ops'

**Comment by CM-BF** [comment]
There is a reminder in mmdetection README page: “The master branch works with PyTorch 1.3 to 1.5. The old v1.x branch works with PyTorch 1.1 to 1.4”.

What can I tell is I had tested it on both PyTorch 1.1 and 1.4 with **mmdetection rc1.0**.  Please check your mmdetection version.

If you wanna use the newest mmdetection version, you may have to find and solve the problem of the function path and possible parameter changes by yourself. : )

**Comment by lseiyjg** [comment]
Thanks. Mmdetection v1.2 solves it. The master branch does not have mmdet.ops.
