### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv'

### ISSUE THREAD

**Issue by Re-bin** [CM-BF/FeatureFlow#6]
Traceback (most recent call last):
  File "eval_Vimeo90K.py", line 13, in <module>
    import src.layers as layers
  File "/content/drive/My Drive/Colab Notebooks/FeatureFlow/src/layers.py", line 1, in <module>
    import src.model as model
  File "/content/drive/My Drive/Colab Notebooks/FeatureFlow/src/model.py", line 6, in <module>
    from mmdet.ops.dcn.deform_conv import DeformConv, ModulatedDeformConv, _pair, modulated_deform_conv
  File "/content/drive/My Drive/Colab Notebooks/mmdetection/mmdet/__init__.py", line 1, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

**Comment by CM-BF** [comment]
Please check your mmdet version. We support the version of 1.0rc.

If you want to use another version of it, please be sure that you know how to modify the code. :)

Thank you.

**Comment by Re-bin** [comment]
> Please check your mmdet version. We support the version of 1.0rc.
> 
> If you want to use another version of it, please be sure that you know how to modify the code. :)
> 
> Thank you.

Thank you for your reply.
I followed your guidence to install the mmdet, but after that the version of mmdet is 2.4.0.
How to install the version of 1.0rc?
Thank you~

**Comment by Re-bin** [comment]
And what is the version of mmcv?
Thank you.

**Comment by CM-BF** [comment]
They have the release here:
https://github.com/open-mmlab/mmdetection/releases/tag/v1.0rc1
It will automatically install mmcv for you. 👍 

If you have more questions about dependencies, please resort to the `requirements.txt` that I have just uploaded.
Thank you.

**Comment by CM-BF** [comment]
If you do not have further questions, I will close this issue.
Thank you.
